In [6]:
def mystery_function1(word):
    vowels = ['a','e','o','u','i']
    while word[0] not in vowels:
        word = word[1:] + word[0]
    return word + 'ay'

In [3]:
def mystery_function2(phrase):
    words = phrase.split()
    new_phrase = [mystery_function1(word) for word in words]
    return ' '.join(new_phrase)

In [7]:
print(mystery_function2('strawberry cheesecake'))

awberrystray eesecakechay


In [9]:
import numpy as np

In [13]:
# create a 7x3 matrix of random numbers
matrix1 = np.random.rand(7,3)
print(matrix1)

[[0.0850966  0.2021148  0.27601045]
 [0.68470728 0.18532927 0.62101111]
 [0.26430876 0.13253604 0.24677755]
 [0.22298924 0.89651341 0.69460171]
 [0.31636176 0.13995356 0.20153753]
 [0.5222628  0.89604659 0.66527039]
 [0.10262504 0.96578524 0.01135444]]


In [12]:
# create a 3,4 matrix of random numbers
matrix2 = np.random.rand(3,4)
print(matrix2)

[[0.643815   0.57737462 0.92394646 0.76872071]
 [0.89384724 0.36477565 0.97049943 0.61792804]
 [0.32166379 0.86340967 0.05534614 0.91369253]]


In [14]:
# multiply matrix1 andd matrix2
matrix3 = np.dot(matrix1, matrix2)

In [15]:
print(matrix3.shape)

(7, 4)


In [16]:
print(matrix3)

[[0.32422879 0.36116927 0.29005311 0.44249661]
 [0.80623766 0.9991232  0.84686538 1.20828203]
 [0.36801232 0.41402121 0.38649148 0.51055616]
 [1.16833807 1.05550042 1.11453938 1.36004961]
 [0.39360287 0.40772035 0.4392805  0.5138184 ]
 [1.3511628  1.20279815 1.38897571 1.56301913]
 [0.93298833 0.42135157 1.03274249 0.68605025]]
